#!/bin/bash

set -eu
set -o pipefail

SCRIPTDIR=$(cd $(dirname $0) && pwd)

HOST=$1
DIR=$2
MAIL_FROM=$3

shift 3

MAIL_TO=$MAIL_FROM

lockfile="$DIR/.lockfile.$HOST"
exec 9> $lockfile
flock -n 9 || {
  >&2 echo "$lockfile is locked"
  exit 1
}

function title()
{
  echo "-------------------------------------------------------------------"
  echo "$@"
  echo "-------------------------------------------------------------------"
}

function mail()
{
  /usr/sbin/sendmail -f $MAIL_FROM $MAIL_TO <<EOF
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
From: $MAIL_FROM
To: $MAIL_TO
Subject: $1

$(cat -)
EOF
}

function epilogue()
{
  rc=$?
  title "rc=$rc, seconds=$SECONDS"
  if [ $rc -ne 0 ] || [ "${SEND_MAIL:-false}" != 'false' ]; then
    test -t 0 || mail "backup $HOST $@ ($rc)" < $out
  fi
  rm $lockfile
  cd "$DIR/log/"
  if [ ! -t 0 ]; then
    find btrfs-backup-*-*.out -mtime 7 -delete
  fi
  exit $rc
}

mkdir -p "$DIR/log/"
out="$DIR/log/btrfs-backup-$(date +%Y%m%d-%H%M).out"

trap epilogue EXIT

if [ ! -t 0 ]; then 
  exec > $out 2>&1
fi

title "$HOST $@"

set +x

$SCRIPTDIR/btrfs-backup --backup-dir=$DIR --host=$HOST $@

exit 0
