#!/bin/bash

set -eu

SCRIPT=$0

function usage()
{
  echo "$SCRIPT IMAGE PART SCRIPT"
  exit 1
}

test $# -eq 3 || usage
test -f $1 || usage
test -s $1 || usage
test -x $3 || usage

IMAGE=$1
PART=$2
SCRIPT=$3

set -x

MP=$(mktemp -d)


function get_nbd()
{
  local size nbd

  modprobe nbd

  (
    cd /sys/devices/virtual/block/
    for nbd in $(ls -d nbd*) ; do
      size=$(cat $nbd/size)
      test $size -eq 0 && break
    done

    echo "/dev/$nbd"
  )
}

NBD=$(get_nbd)

qemu-nbd -c $NBD $IMAGE
udevadm settle; sync

mount ${NBD}p${PART} $MP -o subvol=@rootfs

trap '
cd /tmp
umount ${NBD}p${PART}
qemu-nbd -d $NBD
' EXIT

chattr -R -c $MP/boot

cd $MP
$SCRIPT

chroot $MP /bin/bash <<EOF
set -exu

trap '
umount /proc
umount /dev
umount /sys
' EXIT

mount none -t sysfs /sys
mount none -t devtmpfs /dev
mount none -t proc /proc

echo 'root:root' | chpasswd

cd /etc
mv resolv.conf{,.save}
cat - <<EORC > resolv.conf
nameserver 192.168.9.1
nameserver 192.168.9.6
nameserver 192.168.9.4
EORC

hostnamectl set-hostname `hostnamectl hostname`-nuc

EOF

exit 0
